# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-26 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='t_questions',
            fields=[
                ('questionid', models.AutoField(primary_key=True, serialize=False)),
                ('question_title', models.CharField(max_length=2000)),
            ],
        ),
    ]
