# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-30 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa_message', '0002_auto_20160128_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_messages',
            fields=[
                ('messageid', models.AutoField(primary_key=True, serialize=False)),
                ('messageinfo', models.CharField(max_length=2000)),
                ('questionid', models.IntegerField()),
                ('time', models.TimeField(auto_now=True)),
            ],
        ),
    ]
