# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-30 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa_message', '0003_t_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cur_questionid', models.IntegerField()),
                ('next_questionid', models.IntegerField()),
                ('cur_value', models.CharField(max_length=200)),
            ],
        ),
    ]
