# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-30 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pa_message', '0004_t_module'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='t_module',
            new_name='t_modules',
        ),
    ]
