# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-31 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa_message', '0005_auto_20160330_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_messages',
            name='userid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_questions',
            name='status_reg',
            field=models.CharField(default={}, max_length=2000),
            preserve_default=False,
        ),
    ]
