# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-01 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa_message', '0006_auto_20160331_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_questions',
            name='topicid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
