# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-01 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa_message', '0007_t_questions_topicid'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_questions',
            name='answer_field',
            field=models.CharField(default=' ', max_length=64, verbose_name='answer to field, like username'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_questions',
            name='answer_table',
            field=models.CharField(default=' ', max_length=64, verbose_name='answer to tablename, like user'),
            preserve_default=False,
        ),
    ]
