# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-01 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pa_message', '0008_auto_20160401_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_questions',
            name='answer_table',
        ),
    ]
