# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-01 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa_message', '0009_remove_t_questions_answer_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_user',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('createtime', models.TimeField(auto_now=True)),
            ],
        ),
    ]
