# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-06 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa_message', '0010_t_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_questions',
            name='status_reg',
        ),
        migrations.AddField(
            model_name='t_questions',
            name='proc_func',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_questions',
            name='proc_module',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
    ]
