# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_user',
            name='invitecode',
            field=models.CharField(default='', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
